"""Stage-A spike driver: does the clang front end see everything sipify sees?

Not an emitter.  It answers the four Stage-A questions only:
  1. is every declaration found?
  2. is every SIP_ macro attributed to the right owner?
  3. does anything fall through as unparsed?
  4. does the fail-closed declaration count agree?
"""

from __future__ import annotations

import collections
import re
import sys

import clang.cindex as ci
from sipify import clangenv, exportmacros, tokens
from sipify.preprocess import Output, preprocess
from sipify.sourcefile import SourceFile
from sipify.spans import Span

DECL_KINDS = {
    ci.CursorKind.CXX_METHOD,
    ci.CursorKind.CONSTRUCTOR,
    ci.CursorKind.DESTRUCTOR,
    ci.CursorKind.FUNCTION_TEMPLATE,
    ci.CursorKind.CONVERSION_FUNCTION,
    ci.CursorKind.FUNCTION_DECL,
}
TYPE_KINDS = {
    ci.CursorKind.CLASS_DECL,
    ci.CursorKind.STRUCT_DECL,
    ci.CursorKind.CLASS_TEMPLATE,
    ci.CursorKind.ENUM_DECL,
    ci.CursorKind.NAMESPACE,
}
# Data members, typedefs and aliases: their macros sit on the declaration line.
MEMBER_KINDS = {
    ci.CursorKind.FIELD_DECL,
    ci.CursorKind.VAR_DECL,
    ci.CursorKind.TYPEDEF_DECL,
    ci.CursorKind.TYPE_ALIAS_DECL,
}
# Generated by Q_OBJECT; never part of the public API.
MOC_ARTEFACTS = {
    "metaObject",
    "qt_metacast",
    "qt_metacall",
    "qt_static_metacall",
    "tr",
    "trUtf8",
    "QPrivateSignal",
    "staticMetaObject",
}
# Category C in the macro table: free-standing directives.  They decorate the
# file or open a block of hand-written SIP; there is no declaration to bind
# them to, and several (SIP_NO_FILE, SIP_IF_MODULE) are read by sip_include.sh
# rather than by sipify at all.
DIRECTIVE_MACROS = {
    "SIP_NO_FILE",
    "SIP_IF_MODULE",
    "SIP_FEATURE",
    "SIP_IF_FEATURE",
    "SIP_WHEN_FEATURE",
    "SIP_TYPEHEADER_INCLUDE",
    "SIP_END",
    "SIP_PROPERTY",
    "SIP_CONVERT_TO_SUBCLASS_CODE",
    "SIP_VIRTUAL_CATCHER_CODE",
    "SIP_INSERT_QLIST_ENUM_CONVERSION_CODE",
    "SIP_PYQT5_RUN",
    "SIP_RUN",
}
# `Q_DECLARE_FLAGS( Flags, Flag ) SIP_MONKEYPATCH_FLAGS_UNNEST( ... )` produces
# no cursor at all -- the prelude swallows Q_DECLARE_FLAGS -- so the macro is
# bound to the line rather than to a declaration.
# Constructs that leave no cursor for a macro to bind to, so it binds to the
# line: Q_DECLARE_* (swallowed by the prelude), Q_OBJECT/Q_GADGET, explicit
# template instantiations, friend declarations, and a bare `SIP_SKIP;`.
# A SIP_ macro may lead as well as trail, hence the optional prefix.
LINE_LEVEL = re.compile(
    r"^\s*(?:SIP_[A-Z_]+\s+)?"
    r"(?:Q_DECLARE_\w+|Q_GADGET|Q_OBJECT|template\s+[A-Z_]*_EXPORT|friend\b"
    r"|SIP_[A-Z_]+\s*;?\s*$)"
)


def analyse_header(path: str):
    source = SourceFile.read(path)
    exportmacros.check(path, source.text)
    pre = preprocess(source)
    tu = clangenv.parse(path, pre.clang_text)
    text = source.text

    def off(loc):
        return source.offset(loc.line, loc.column)

    found, attributed, unowned = [], [], []
    # Macros are written on either side of what they decorate --
    # `SIP_SKIP QgsFoo( QgsFoo && );` as often as `void f() SIP_FACTORY;` -- so
    # a declaration's scan starts at its line, not at its first token.  Clamped
    # to the previous declaration's end so two on one line cannot steal from
    # each other.
    prev_end = 0

    def scan_start(cursor_off: int) -> int:
        line_start = source.line_span(source.position(cursor_off)[0]).start
        # walk_preorder is not strictly source-ordered (a nested class's members
        # follow the class), so prev_end can sit past this cursor; never let the
        # scan run backwards.
        return min(max(line_start, prev_end), cursor_off)

    for cursor in tu.cursor.walk_preorder():
        loc = cursor.location
        if not loc.file or loc.file.name != path:
            continue
        if cursor.spelling in MOC_ARTEFACTS:
            continue
        line = loc.line
        if pre.output_of(line) is not Output.EMIT:
            continue

        if cursor.kind in TYPE_KINDS:
            found.append((cursor.kind.name, cursor.spelling, line))
            head = tokens.head_span(text, off(cursor.extent.start))
            for use in tokens.macro_uses(text, head):
                attributed.append((use, "type", cursor.spelling, line))
            if cursor.kind is ci.CursorKind.ENUM_DECL:
                # Enumerators carry their macros the same way parameters do:
                # each one's slice runs to the start of the next.
                consts = [
                    c
                    for c in cursor.get_children()
                    if c.kind is ci.CursorKind.ENUM_CONSTANT_DECL
                ]
                starts = [off(c.extent.start) for c in consts]
                body_end = off(cursor.extent.end)
                for k, const in enumerate(consts):
                    stop = starts[k + 1] if k + 1 < len(starts) else body_end
                    for use in tokens.macro_uses(text, Span(starts[k], stop)):
                        attributed.append(
                            (use, "enumerator", const.spelling, const.location.line)
                        )
            continue

        if cursor.kind in MEMBER_KINDS:
            found.append((cursor.kind.name, cursor.spelling, line))
            begin = off(cursor.extent.start)
            span = Span(scan_start(begin), tokens.declaration_end(text, begin))
            for use in tokens.macro_uses(text, span):
                attributed.append((use, "member", cursor.spelling, line))
            prev_end = span.end
            continue

        if cursor.kind not in DECL_KINDS:
            continue

        found.append((cursor.kind.name, cursor.spelling, line))
        begin = off(cursor.extent.start)
        starts = [off(p.extent.start) for p in cursor.get_arguments()]
        sig = tokens.analyse(text, begin, starts)
        # Everything up to the parameter list: the prefix before clang's first
        # token (`SIP_SKIP QgsFoo( QgsFoo && );`) and the return-type region
        # (`QAtomicInt SIP_PYALTERNATIVETYPE( int ) refs() const;`).
        head_end = sig.paren_open if sig.paren_open is not None else sig.span.end
        for use in tokens.macro_uses(text, Span(scan_start(begin), head_end)):
            attributed.append((use, "method", cursor.spelling, line))
        for i, sl in enumerate(sig.arg_slices):
            for use in tokens.macro_uses(text, sl):
                attributed.append((use, f"arg:{i}", cursor.spelling, line))
        if sig.trailer:
            for use in tokens.macro_uses(text, sig.trailer):
                attributed.append((use, "method", cursor.spelling, line))
        prev_end = sig.span.end

    # Q_DECLARE_FLAGS lines leave no cursor behind; bind their macros by line.
    for n in range(1, source.line_count + 1):
        if pre.output_of(n) is not Output.EMIT:
            continue
        raw = source.lines[n - 1]
        if LINE_LEVEL.match(raw):
            for use in tokens.macro_uses(text, source.line_span(n)):
                attributed.append((use, "line", raw.strip(), n))

    # Every SIP_ macro on an EMIT line must have found an owner.
    claimed = {u.span for u, _, _, _ in attributed}
    for use in tokens.macro_uses(text, Span(0, len(text))):
        line = source.position(use.span.start)[0]
        if pre.output_of(line) is not Output.EMIT:
            continue
        if use.name in DIRECTIVE_MACROS or use.span in claimed:
            continue
        unowned.append((use, line))
    return source, pre, found, attributed, unowned


def main(paths: list[str]) -> int:
    totals = collections.Counter()
    unowned_by_macro = collections.Counter()
    problems = []
    for path in paths:
        try:
            src, pre, found, attributed, unowned = analyse_header(path)
        except Exception as exc:  # noqa: BLE001
            problems.append((path, f"{type(exc).__name__}: {exc}"))
            totals["failed"] += 1
            continue
        totals["headers"] += 1
        totals["decls"] += len(found)
        totals["macros_attributed"] += len(attributed)
        totals["macros_unowned"] += len(unowned)
        for use, line in unowned:
            unowned_by_macro[use.name] += 1
            if len(problems) < 25:
                problems.append(
                    (
                        path,
                        f"unowned {use} at line {line}: "
                        f"{src.lines[line - 1].strip()[:70]}",
                    )
                )
    print(f"headers          : {totals['headers']}  (failed: {totals['failed']})")
    print(f"declarations     : {totals['decls']}")
    print(f"macros attributed: {totals['macros_attributed']}")
    print(f"macros unowned   : {totals['macros_unowned']}")
    if unowned_by_macro:
        print("unowned by macro :", dict(unowned_by_macro.most_common(12)))
    for path, msg in problems[:25]:
        print(f"   {path}: {msg}")
    return 1 if totals["failed"] or totals["macros_unowned"] else 0


if __name__ == "__main__":
    args = sys.argv[1:]
    if len(args) == 1 and args[0].endswith(".txt"):
        args = [l.strip() for l in open(args[0]) if l.strip()]
    raise SystemExit(main(args))
