name: Auto set milestone on PR

on:
  pull_request:
    types:
      - opened
      -

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # obfuscate the github token so it can be used on jobs triggered from forks
      - name: Clear GH Token
        id: token
        uses: opengisch/clear-token@v1.0.12
        with:
          bot_token_encrypted: ddbdec32940df79f1adf2369b4b10f10b5a66f65
          bot_token_xor_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c

      # list the tags
      - name: List tags
        uses: octokit/request-action@v2.x
        id: list_tags
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        with:
          route: GET /repos/qgis/QGIS/git/tags

      # extracts the matching commits
      - name: Get the latest release
        id: latest_release
        env:
          JSON_DATA: ${{ steps.list_branches.outputs.data }}
        run: |
          echo ${JSON_DATA}
          COMMITS_MESSAGES=$(echo ${JSON_DATA} | jq '.[].commit.message | select( . |test("\\[(feature|needs?.doc(umentation)?s?)\\]"; "i")) | sub("\\[needs?.doc(umentation)?s?\\]"; "\n\n\n\n"; "i")')
          echo "::set-output name=commits::$(echo ${COMMITS_MESSAGES} | tr -d '\n' )"    -
