name: Run sipify on PR

on:
  issue_comment:
    types: [created]

jobs:
  sipify:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '@sipify')
    runs-on: [ubuntu-latest]
    steps:

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - run: |
          echo "github.event.pull_request.head.repo.base_ref: ${{ github.base_ref }}"
          echo "github.event.pull_request.head.repo.head_ref: ${{ github.head_ref }}"
          echo "comment-head_ref: ${{ steps.comment-branch.outputs.head_ref }}"
          echo "comment-base_ref: ${{ steps.comment-branch.outputs.base_ref }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          #ref: ${{ github.event.pull_request.head.repo.base_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Requirements
        run: |
          sudo apt install -y \
              cpanminus \
              libyaml-tiny-perl \
              libio-socket-ssl-perl \
              libhttp-date-perl \
              libgetopt-long-descriptive-perl \
              libmoo-perl \
              libnamespace-clean-perl \
              libpath-tiny-perl \
              libpod-constants-perl \
              libscalar-list-utils-perl \
              libsort-key-perl \
              libstrictures-perl \
              libstring-escape-perl \
              libtry-tiny-perl

      - name: run sipify
        run: ./scripts/sipify_all.sh

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto sipify 🍺"
          git push
